name: php.yml

on:
  push:
    branches: [ "master", "create-workflow" ]
  pull_request:
    branches: [ "master", "create-workflow" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    services:
          mysql:
            image: mysql:8.0
            env:
              # The MySQL docker container requires these environment variables to be set
              # so we can create and migrate the test database.
              # See: https://hub.docker.com/_/mysql
              MYSQL_DATABASE: testdb
              MYSQL_ROOT_PASSWORD: testrootpass
            ports:
              # Opens port 3306 on service container and host
              # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
              - 3306:3306
              # Before continuing, verify the mysql container is reachable from the ubuntu host
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run tests
      # These environment variables will take precedence over the ones in the Django settings file
      env:
        # Set the DJANGO_SECRET_KEY in the Github repo settings: Go to Secrets and variables > Actions > New repository secret 
        DATABASE_NAME: testdb
        DATABASE_USERNAME: root          
        DATABASE_PASSWORD: testrootpass          
        DATABASE_ENDPOINT: 127.0.0.1 # Will not work with 'localhost', since that will try a Unix socket connection (!)
      run: vendor/bin/phpunit tests
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
