name: PHPUnit

on:
  push:
    branches: [ "master", "create-workflow" ]
  pull_request:
    branches: [ "master", "create-workflow" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: test
      DB_USER: root
      DB_PASSWORD: root
    steps:
    - uses: actions/checkout@v4

    - name: Set up MySQL
      run: |
        sudo systemctl start mysql.service
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Copy import files for mysql
      env:
        DATABASE_NAME: test
        DATABASE_USERNAME: root
        DATABASE_PASSWORD: root
        DATABASE_ENDPOINT: 127.0.0.1
      run: |
        # ls ${{ github.workspace }}/tests/data/* " 
        sudo cp tests/data/* /var/lib/mysql-files

    - name: Copy php .env file
      run: |
        cp .github/workflows/.env .env

    - name: Run tests
      env:
        DATABASE_NAME: test
        DATABASE_USERNAME: root
        DATABASE_PASSWORD: root
        DATABASE_ENDPOINT: 127.0.0.1
      run: |
        vendor/bin/phpunit tests
